window.BANK_KELAS_7 = {
  info: { kelas: "7", label: "Kelas 7" },
  paket: [
    {
      id: "paket-01",
      judul: "Bilangan Bulat",
      deskripsi: "Operasi penjumlahan, pengurangan, perkalian, pembagian, serta soal cerita kontekstual.",
      soal: [
        { tipe: "pgk", q: "Hasil operasi berikut yang sama dengan −12 adalah ....",
          options: ["4 × (−3)", "(−6) + (−6)", "24 ÷ (−2)", "(−15) − 3"],
          kunci: [0,1,2],
          bahas: "4 × (−3) = −12, (−6) + (−6) = −12, dan 24 ÷ (−2) = −12. Sementara (−15) − 3 = −18." },
        { tipe: "pgk", q: "Operasi berikut yang hasilnya −8 adalah ....",
          options: ["(−2) + 6", "(−5) + (−3)", "16 ÷ 2", "(−4) × 2"],
          kunci: [1,3],
          bahas: "(−5) + (−3) = −8 dan (−4) × 2 = −8. Pilihan lain: (−2) + 6 = 4 dan 16 ÷ 2 = 8." },
        { tipe: "pgk", q: "Pernyataan yang benar tentang bilangan bulat adalah ....",
          options: ["Hasil kali dua bilangan negatif adalah positif", "−7 > −3", "Lawan dari 12 adalah −12", "(−10) ÷ 2 = −5"],
          kunci: [0,2,3],
          bahas: "Negatif kali negatif hasilnya positif, lawan dari 12 adalah −12, dan (−10) ÷ 2 = −5. Namun −7 < −3 karena posisinya lebih ke kiri pada garis bilangan." },
        { tipe: "bs", q: "Pernyataan: (−8) − (−5) = −3.",
          kunci: true,
          bahas: "(−8) − (−5) = (−8) + 5 = −3, jadi pernyataan benar." },
        { tipe: "bs", q: "Pernyataan: Hasil dari 15 ÷ (−3) + 2 adalah −7.",
          kunci: false,
          bahas: "15 ÷ (−3) = −5, lalu −5 + 2 = −3, bukan −7." },
        { tipe: "bs", q: "Pernyataan: Urutan −9, −4, 0, 5 dari yang terkecil sudah benar.",
          kunci: true,
          bahas: "Pada garis bilangan −9 < −4 < 0 < 5, jadi urutannya benar." },
        { tipe: "jodoh", q: "Pasangkan setiap operasi pada kolom kiri dengan hasilnya yang tepat.",
          items: ["(−7) + 12", "15 − (−8)", "−4 × 6"],
          options: ["5", "23", "−24", "−9"],
          kunci: [0,1,2],
          bahas: "(−7) + 12 = 5; 15 − (−8) = 15 + 8 = 23; −4 × 6 = −24." },
        { tipe: "jodoh", q: "Pasangkan setiap pernyataan pada kolom kiri dengan nilainya yang tepat.",
          items: ["Hasil dari (−2)³", "Hasil dari 100 ÷ (−25)", "Lawan dari 18"],
          options: ["−8", "−4", "−18", "8"],
          kunci: [0,1,2],
          bahas: "(−2)³ = −8; 100 ÷ (−25) = −4; lawan dari 18 adalah −18." },
        { tipe: "isian", q: "Suhu mula-mula −6°C, kemudian naik 15°C. Suhu akhirnya adalah .... °C",
          kunci: ["9"],
          bahas: "−6 + 15 = 9, jadi suhu akhirnya 9°C." },
        { tipe: "isian", q: "Hasil dari (−12) ÷ 3 × (−2) = ....",
          kunci: ["8"],
          bahas: "(−12) ÷ 3 = −4, lalu (−4) × (−2) = 8." }
      ]
    },
    {
      id: "paket-02",
      judul: "Bilangan Rasional",
      deskripsi: "Mengubah bentuk pecahan, desimal, persen, dan operasi hitung rasional.",
      soal: [
        { tipe: "pgk", q: "Pecahan berikut yang senilai dengan ¾ adalah ....",
          options: ["6/8", "9/16", "12/16", "15/24"],
          kunci: [0,2],
          bahas: "6/8 = 3/4 dan 12/16 = 3/4. Sedangkan 9/16 ≠ 3/4 dan 15/24 = 5/8." },
        { tipe: "pgk", q: "Bentuk desimal dari pecahan berikut yang benar adalah ....",
          options: ["½ = 0,2", "¾ = 0,75", "⅖ = 0,4", "⅞ = 0,875"],
          kunci: [1,2,3],
          bahas: "¾ = 0,75; ⅖ = 0,4; ⅞ = 0,875. Namun ½ = 0,5 bukan 0,2." },
        { tipe: "pgk", q: "Hasil operasi berikut yang bernilai lebih dari 1 adalah ....",
          options: ["½ + ¾", "⅔ × ¾", "0,5 + 0,25", "1¼ − 0,1"],
          kunci: [0,3],
          bahas: "½ + ¾ = 5/4 = 1,25 > 1 dan 1¼ − 0,1 = 1,15 > 1. Sedangkan ⅔ × ¾ = ½ dan 0,5 + 0,25 = 0,75." },
        { tipe: "bs", q: "Pernyataan: 0,5 + ⅓ = ⅚.",
          kunci: true,
          bahas: "0,5 = ½, dan ½ + ⅓ = 3/6 + 2/6 = 5/6." },
        { tipe: "bs", q: "Pernyataan: 40% dari 250 adalah 120.",
          kunci: false,
          bahas: "40% × 250 = 100, bukan 120." },
        { tipe: "bs", q: "Pernyataan: −½ > −¾.",
          kunci: true,
          bahas: "−0,5 lebih besar dari −0,75 karena posisinya lebih ke kanan pada garis bilangan." },
        { tipe: "jodoh", q: "Pasangkan setiap pecahan pada kolom kiri dengan bentuk persennya yang tepat.",
          items: ["½", "¼", "⅗"],
          options: ["25%", "60%", "50%", "75%"],
          kunci: [2,0,1],
          bahas: "½ = 50%; ¼ = 25%; ⅗ = 60%." },
        { tipe: "jodoh", q: "Pasangkan setiap operasi pada kolom kiri dengan hasilnya yang tepat.",
          items: ["⅔ + ⅙", "0,8 − 0,35", "50% × 8"],
          options: ["⅚", "0,45", "4", "0,55"],
          kunci: [0,1,2],
          bahas: "⅔ + ⅙ = 5/6; 0,8 − 0,35 = 0,45; 50% × 8 = 4." },
        { tipe: "isian", q: "Hasil dari ¾ + 0,5 dalam bentuk desimal adalah ....",
          kunci: ["1,25", "1.25"],
          bahas: "¾ = 0,75, sehingga 0,75 + 0,5 = 1,25." },
        { tipe: "isian", q: "25% dari 80 = ....",
          kunci: ["20"],
          bahas: "25% × 80 = ¼ × 80 = 20." }
      ]
    },
    {
      id: "paket-03",
      judul: "Aritmetika Sosial",
      deskripsi: "Persentase untung/rugi, diskon belanja, bunga tunggal, dan bruto-neto-tara.",
      soal: [
        { tipe: "pgk", q: "Pedagang membeli barang Rp40.000,00 lalu menjualnya Rp46.000,00. Pernyataan yang benar adalah ....",
          options: ["Keuntungannya Rp6.000,00", "Persentase keuntungannya 15%", "Harga jual lebih kecil dari harga beli", "Transaksi tersebut untung"],
          kunci: [0,1,3],
          bahas: "Untung = 46.000 − 40.000 = 6.000; persentasenya 6.000/40.000 × 100% = 15%. Harga jual jelas lebih besar dari harga beli." },
        { tipe: "pgk", q: "Sepatu Rp200.000,00 didiskon 25%. Pernyataan yang benar adalah ....",
          options: ["Besar diskon Rp25.000,00", "Besar diskon Rp50.000,00", "Harga yang dibayar Rp150.000,00", "Harga yang dibayar Rp175.000,00"],
          kunci: [1,2],
          bahas: "Diskon = 25% × 200.000 = 50.000, sehingga harga bayar = 200.000 − 50.000 = 150.000." },
        { tipe: "pgk", q: "Bruto suatu barang 50 kg dengan tara 2%. Pernyataan yang benar adalah ....",
          options: ["Tara = 1 kg", "Neto = 52 kg", "Neto = 49 kg", "Tara = 2 kg"],
          kunci: [0,2],
          bahas: "Tara = 2% × 50 = 1 kg, sehingga neto = 50 − 1 = 49 kg." },
        { tipe: "bs", q: "Pernyataan: Bunga tunggal 10% per tahun dari modal Rp1.000.000,00 selama 2 tahun adalah Rp200.000,00.",
          kunci: true,
          bahas: "Bunga = 10% × 1.000.000 × 2 = 200.000." },
        { tipe: "bs", q: "Pernyataan: Harga beli Rp80.000,00 dijual Rp72.000,00 berarti rugi 10%.",
          kunci: true,
          bahas: "Rugi = 8.000 dan 8.000/80.000 × 100% = 10%." },
        { tipe: "bs", q: "Pernyataan: Diskon 20% lalu 10% sama dengan diskon 30%.",
          kunci: false,
          bahas: "Diskon berturut-turut: 0,8 × 0,9 = 0,72 artinya total diskon 28%, bukan 30%." },
        { tipe: "jodoh", q: "Pasangkan setiap istilah pada kolom kiri dengan artinya yang tepat.",
          items: ["Bruto", "Neto", "Tara"],
          options: ["Berat kemasan", "Berat kotor", "Berat bersih", "Harga jual"],
          kunci: [1,2,0],
          bahas: "Bruto = berat kotor, neto = berat bersih, tara = berat kemasan." },
        { tipe: "jodoh", q: "Pasangkan setiap pernyataan pada kolom kiri dengan nilainya yang tepat.",
          items: ["Besar keuntungan 20% dari modal Rp50.000", "Besar kerugian 10% dari modal Rp50.000", "Besar diskon 50% dari harga Rp90.000"],
          options: ["Rp10.000", "Rp5.000", "Rp45.000", "Rp25.000"],
          kunci: [0,1,2],
          bahas: "20% × 50.000 = 10.000; 10% × 50.000 = 5.000; 50% × 90.000 = 45.000." },
        { tipe: "isian", q: "Modal Rp600.000,00 dengan keuntungan 12%. Harga jualnya Rp .... (tulis angka saja)",
          kunci: ["672000", "672.000"],
          bahas: "Harga jual = 600.000 × 112% = 672.000." },
        { tipe: "isian", q: "Bruto 25 kg dan neto 24,5 kg. Tara = .... kg",
          kunci: ["0,5", "0.5", "1/2"],
          bahas: "Tara = bruto − neto = 25 − 24,5 = 0,5 kg." }
      ]
    },
    {
      id: "paket-04",
      judul: "Data dan Diagram",
      deskripsi: "Penyajian data diagram batang/lingkaran, serta mean, median, dan modus.",
      soal: [
        { tipe: "pgk", q: "Data: 4, 6, 6, 8, 8, 8, 9. Pernyataan yang benar adalah ....",
          options: ["Modus = 8", "Median = 6", "Rata-rata = 7", "Banyak data = 7"],
          kunci: [0,2,3],
          bahas: "Modus (paling sering muncul) = 8; rata-rata = 49/7 = 7; banyak data = 7. Median data terurut adalah 8, bukan 6." },
        { tipe: "pgk", q: "Diagram lingkaran kegemaran 40 siswa: sepak bola 30%, basket 25%, voli 20%, lainnya 25%. Pernyataan yang benar adalah ....",
          options: ["Gemar sepak bola 12 siswa", "Gemar voli 8 siswa", "Gemar lainnya 12 siswa", "Gemar basket 10 siswa"],
          kunci: [0,1,3],
          bahas: "30% × 40 = 12; 20% × 40 = 8; 25% × 40 = 10. Jadi yang gemar 'lainnya' ada 10 siswa, bukan 12." },
        { tipe: "pgk", q: "Nilai ulangan: 6, 7, 8, 5, 9, 7, 6, 6. Pernyataan yang benar adalah ....",
          options: ["Rata-rata = 7", "Modus = 6", "Median = 6,5", "Data terbesar = 9"],
          kunci: [1,2,3],
          bahas: "Jumlah = 54 sehingga rata-rata = 6,75; modus = 6 (muncul 3 kali); median = (6+7)/2 = 6,5; data terbesar = 9." },
        { tipe: "bs", q: "Pernyataan: Median dari 3, 5, 7, 9, 11 adalah 7.",
          kunci: true,
          bahas: "Data sudah terurut dan nilai tengahnya (data ke-3) adalah 7." },
        { tipe: "bs", q: "Pernyataan: Rata-rata dari 10, 20, 30 adalah 15.",
          kunci: false,
          bahas: "(10 + 20 + 30) ÷ 3 = 20, bukan 15." },
        { tipe: "bs", q: "Pernyataan: Diagram batang cocok untuk membandingkan banyak data antar-kelompok.",
          kunci: true,
          bahas: "Diagram batang memang digunakan untuk membandingkan frekuensi antar-kelompok data." },
        { tipe: "jodoh", q: "Pasangkan setiap kumpulan data pada kolom kiri dengan rata-ratanya yang tepat.",
          items: ["3, 3, 6", "10, 20", "4, 8, 12"],
          options: ["4", "15", "8", "6"],
          kunci: [0,1,2],
          bahas: "(3+3+6) ÷ 3 = 4; (10+20) ÷ 2 = 15; (4+8+12) ÷ 3 = 8." },
        { tipe: "jodoh", q: "Pasangkan setiap istilah statistika pada kolom kiri dengan artinya yang tepat.",
          items: ["Mean", "Median", "Modus"],
          options: ["Nilai tengah data terurut", "Nilai rata-rata", "Nilai yang paling sering muncul", "Nilai terbesar"],
          kunci: [1,0,2],
          bahas: "Mean = nilai rata-rata; median = nilai tengah data terurut; modus = nilai yang paling sering muncul." },
        { tipe: "isian", q: "Rata-rata dari 6, 8, 10, dan x adalah 8. Nilai x = ....",
          kunci: ["8"],
          bahas: "(6 + 8 + 10 + x) ÷ 4 = 8 → 24 + x = 32 → x = 8." },
        { tipe: "isian", q: "Median dari 4, 7, 9, 12, 15 adalah ....",
          kunci: ["9"],
          bahas: "Data sudah terurut dan nilai tengahnya adalah 9." }
      ]
    },
    {
      id: "paket-05",
      judul: "Bentuk Aljabar",
      deskripsi: "Penjumlahan, pengurangan, perkalian suku aljabar, dan penyederhanaan bentuk aljabar.",
      soal: [
        { tipe: "pgk", q: "Bentuk aljabar berikut yang senilai dengan 5x − 2 adalah ....",
          options: ["(3x + 5) + (2x − 7)", "(8x + 1) − (3x + 3)", "2(3x − 1) − x", "(x + 4) + (4x + 2)"],
          kunci: [0,1,2],
          bahas: "(3x+5)+(2x−7) = 5x−2; (8x+1)−(3x+3) = 5x−2; 2(3x−1)−x = 5x−2. Sedangkan (x+4)+(4x+2) = 5x+6." },
        { tipe: "pgk", q: "Hasil perkalian bentuk aljabar berikut yang benar adalah ....",
          options: ["3x(2x + 1) = 6x² + 3x", "(x + 2)(x + 3) = x² + 5x + 5", "2a(a − 4) = 2a² − 8a", "(x − 1)² = x² − 1"],
          kunci: [0,2],
          bahas: "3x(2x+1) = 6x²+3x dan 2a(a−4) = 2a²−8a. Yang benar: (x+2)(x+3) = x²+5x+6 dan (x−1)² = x²−2x+1." },
        { tipe: "pgk", q: "Pasangan suku-suku sejenis ditunjukkan oleh ....",
          options: ["3x dan 3y", "5ab dan −2ab", "4x² dan 4x", "−7p dan 2p"],
          kunci: [1,3],
          bahas: "Suku sejenis memiliki variabel dan pangkat yang sama: 5ab dengan −2ab, serta −7p dengan 2p." },
        { tipe: "bs", q: "Pernyataan: 4x − 2x + 7x = 9x.",
          kunci: true,
          bahas: "(4 − 2 + 7)x = 9x." },
        { tipe: "bs", q: "Pernyataan: Koefisien dari −5y² adalah 5.",
          kunci: false,
          bahas: "Koefisiennya adalah −5, bukan 5." },
        { tipe: "bs", q: "Pernyataan: (x + 3)(x − 3) = x² − 9.",
          kunci: true,
          bahas: "(x+3)(x−3) = x² − 3x + 3x − 9 = x² − 9." },
        { tipe: "jodoh", q: "Pasangkan setiap bentuk aljabar pada kolom kiri dengan bentuk sederhananya yang tepat.",
          items: ["2x + 3x", "5y − 2y", "x + 2x + 3x"],
          options: ["3y", "6x", "5x", "7x"],
          kunci: [2,0,1],
          bahas: "2x+3x = 5x; 5y−2y = 3y; x+2x+3x = 6x." },
        { tipe: "jodoh", q: "Pasangkan setiap perkalian pada kolom kiri dengan hasilnya yang tepat.",
          items: ["x(x + 5)", "2(x − 3)", "3x · 2x"],
          options: ["x² + 5x", "2x − 6", "6x²", "x² + 6"],
          kunci: [0,1,2],
          bahas: "x(x+5) = x²+5x; 2(x−3) = 2x−6; 3x · 2x = 6x²." },
        { tipe: "isian", q: "Hasil dari 7a − 3a + 2a = ....a (tulis koefisiennya saja)",
          kunci: ["6"],
          bahas: "(7 − 3 + 2)a = 6a." },
        { tipe: "isian", q: "Jika x = 4, nilai dari 3x − 5 = ....",
          kunci: ["7"],
          bahas: "3(4) − 5 = 12 − 5 = 7." }
      ]
    },
    {
      id: "paket-06",
      judul: "Garis dan Sudut",
      deskripsi: "Jenis-jenis sudut, sudut berpelurus/berpenyiku, dan hubungan sudut pada garis sejajar.",
      soal: [
        { tipe: "pgk", q: "Dua sudut saling berpenyiku dan salah satunya 35°. Pernyataan yang benar adalah ....",
          options: ["Sudut yang lain 55°", "Jumlah keduanya 180°", "Keduanya merupakan sudut lancip", "Sudut yang lain 145°"],
          kunci: [0,2],
          bahas: "Sudut yang lain = 90° − 35° = 55°. Keduanya lancip karena kurang dari 90°." },
        { tipe: "pgk", q: "Pasangan sudut yang saling berpelurus adalah ....",
          options: ["60° dan 30°", "120° dan 60°", "90° dan 90°", "45° dan 45°"],
          kunci: [1,2],
          bahas: "Berpelurus berarti jumlahnya 180°: 120+60 = 180 dan 90+90 = 180. Dua pasangan lainnya jumlahnya 90° (berpenyiku)." },
        { tipe: "pgk", q: "Dua garis sejajar dipotong sebuah garis transversal. Pernyataan yang benar adalah ....",
          options: ["Sudut-sudut sehadap sama besar", "Sudut-sudut berseberangan sama besar", "Sudut-sudut sepihak sama besar", "Sudut-sudut bertolak belakang sama besar"],
          kunci: [0,1,3],
          bahas: "Sehadap sama besar, berseberangan sama besar, dan bertolak belakang sama besar. Sudut sepihak jumlahnya 180°, bukan sama besar." },
        { tipe: "bs", q: "Pernyataan: Sudut 100° termasuk sudut lancip.",
          kunci: false,
          bahas: "100° lebih dari 90° sehingga termasuk sudut tumpul." },
        { tipe: "bs", q: "Pernyataan: Penyiku dari 40° adalah 50°.",
          kunci: true,
          bahas: "40° + 50° = 90°, jadi benar." },
        { tipe: "bs", q: "Pernyataan: Jumlah dua sudut yang berpelurus adalah 90°.",
          kunci: false,
          bahas: "Berpelurus berarti jumlahnya 180°, bukan 90°." },
        { tipe: "jodoh", q: "Pasangkan setiap besar sudut pada kolom kiri dengan jenisnya yang tepat.",
          items: ["45°", "90°", "130°"],
          options: ["Siku-siku", "Tumpul", "Lancip", "Refleks"],
          kunci: [2,0,1],
          bahas: "45° lancip (< 90°); 90° siku-siku; 130° tumpul (antara 90° dan 180°)." },
        { tipe: "jodoh", q: "Pasangkan setiap pasangan sudut pada kolom kiri dengan jumlahnya yang tepat.",
          items: ["30° dan 60°", "110° dan 70°", "90° dan 45°"],
          options: ["90°", "180°", "135°", "150°"],
          kunci: [0,1,2],
          bahas: "30+60 = 90; 110+70 = 180; 90+45 = 135." },
        { tipe: "isian", q: "Sudut yang berpelurus dengan 115° besarnya ....°",
          kunci: ["65"],
          bahas: "180° − 115° = 65°." },
        { tipe: "isian", q: "Besar sudut terkecil yang dibentuk jarum jam pada pukul 03.00 adalah ....°",
          kunci: ["90"],
          bahas: "Pukul 03.00 jarum pendek di angka 3 dan jarum panjang di angka 12, membentuk sudut siku-siku 90°." }
      ]
    },
    {
      id: "paket-07",
      judul: "Persamaan Linear Satu Variabel",
      deskripsi: "Pemodelan aljabar dan penyelesaian himpunan solusi.",
      soal: [
        { tipe: "pgk", q: "Persamaan berikut yang ekuivalen dengan 2x = 10 adalah ....",
          options: ["x = 5", "4x = 20", "x + 3 = 8", "3x = 12"],
          kunci: [0,1,2],
          bahas: "2x = 10 → x = 5. Yang ekuivalen: 4x = 20 (x = 5) dan x + 3 = 8 (x = 5). Sedangkan 3x = 12 → x = 4." },
        { tipe: "pgk", q: "Pernyataan yang benar tentang persamaan 4x + 5 = 21 adalah ....",
          options: ["Penyelesaiannya x = 4", "Jika x = 5 maka ruas kiri = 21", "Bentuk ekuivalennya 4x = 26", "x = 4 memenuhi persamaan"],
          kunci: [0,3],
          bahas: "4x = 16 → x = 4, dan 4(4)+5 = 21 memang benar. Jika x = 5, ruas kiri = 25; bentuk ekuivalennya 4x = 16." },
        { tipe: "pgk", q: "Kalimat berikut yang dapat dimodelkan dengan 2x + 7 = 25 adalah ....",
          options: ["Dua kali bilangan x adalah 25", "Jumlah dua kali suatu bilangan dengan 7 adalah 25", "Tujuh ditambah dua kali suatu bilangan sama dengan 25", "Selisih dua kali suatu bilangan dengan 7 adalah 25"],
          kunci: [1,2],
          bahas: "2x + 7 = 25 dibaca 'dua kali suatu bilangan ditambah 7 sama dengan 25'." },
        { tipe: "bs", q: "Pernyataan: Penyelesaian dari x + 9 = 20 adalah x = 11.",
          kunci: true,
          bahas: "x = 20 − 9 = 11." },
        { tipe: "bs", q: "Pernyataan: Jika 5x = 45 maka x = 8.",
          kunci: false,
          bahas: "x = 45 ÷ 5 = 9, bukan 8." },
        { tipe: "bs", q: "Pernyataan: Persamaan 2x − 6 = 0 ekuivalen dengan x = 3.",
          kunci: true,
          bahas: "2x = 6 → x = 3, jadi ekuivalen." },
        { tipe: "jodoh", q: "Pasangkan setiap persamaan pada kolom kiri dengan penyelesaiannya yang tepat.",
          items: ["x + 5 = 12", "2x = 18", "x − 4 = 10"],
          options: ["9", "14", "7", "10"],
          kunci: [2,0,1],
          bahas: "x + 5 = 12 → x = 7; 2x = 18 → x = 9; x − 4 = 10 → x = 14." },
        { tipe: "jodoh", q: "Pasangkan setiap kalimat pada kolom kiri dengan model matematikanya yang tepat.",
          items: ["Lima ditambah suatu bilangan sama dengan 17", "Dua kali suatu bilangan sama dengan 30", "Suatu bilangan dikurangi 9 sama dengan 6"],
          options: ["x + 5 = 17", "2x = 30", "x − 9 = 6", "x + 9 = 6"],
          kunci: [0,1,2],
          bahas: "Langsung diterjemahkan: x + 5 = 17; 2x = 30; x − 9 = 6." },
        { tipe: "isian", q: "Penyelesaian dari 6x − 3 = 27 adalah x = ....",
          kunci: ["5"],
          bahas: "6x = 30 → x = 5." },
        { tipe: "isian", q: "Jumlah tiga bilangan berurutan adalah 48. Bilangan terkecilnya adalah ....",
          kunci: ["15"],
          bahas: "x + (x+1) + (x+2) = 48 → 3x + 3 = 48 → x = 15." }
      ]
    },
    {
      id: "paket-08",
      judul: "Kesebangunan",
      deskripsi: "Perbandingan skala denah/foto, bayangan objek, dan sifat kesebangunan geometri.",
      soal: [
        { tipe: "pgk", q: "Dua bangun datar dikatakan sebangun jika ....",
          options: ["Sudut-sudut yang bersesuaian sama besar", "Sisi-sisi yang bersesuaian sebanding", "Semua sisinya sama panjang", "Bentuknya sama tetapi ukurannya boleh berbeda"],
          kunci: [0,1,3],
          bahas: "Syarat sebangun: sudut bersesuaian sama besar dan sisi bersesuaian sebanding. 'Semua sisi sama panjang' adalah syarat kongruen." },
        { tipe: "pgk", q: "Denah berskala 1 : 200. Jarak pada denah 5 cm. Pernyataan yang benar adalah ....",
          options: ["Jarak sebenarnya 100 m", "Jarak sebenarnya 10 m", "Jarak sebenarnya 1.000 cm", "1 cm pada denah = 200 m sebenarnya"],
          kunci: [1,2],
          bahas: "Jarak sebenarnya = 5 × 200 = 1.000 cm = 10 m. Skala 1:200 artinya 1 cm = 200 cm = 2 m." },
        { tipe: "pgk", q: "Tiang setinggi 4 m memiliki bayangan 6 m. Pada saat yang sama bayangan sebuah pohon 9 m. Pernyataan yang benar adalah ....",
          options: ["Tinggi pohon 8 m", "Perbandingan tinggi : bayangan = 3 : 2", "Tinggi pohon 6 m", "Perbandingan tinggi : bayangan = 2 : 3"],
          kunci: [2,3],
          bahas: "4/6 = t/9 → t = 6 m. Perbandingan tinggi : bayangan = 4 : 6 = 2 : 3." },
        { tipe: "bs", q: "Pernyataan: Semua persegi sebangun.",
          kunci: true,
          bahas: "Semua sudut persegi 90° dan sisi-sisinya selalu sebanding." },
        { tipe: "bs", q: "Pernyataan: Dua segitiga siku-siku selalu sebangun.",
          kunci: false,
          bahas: "Sudut lancipnya bisa berbeda, misalnya 30°-60° dan 45°-45°, sehingga belum tentu sebangun." },
        { tipe: "bs", q: "Pernyataan: Skala 1 : 500 artinya 1 cm pada gambar = 5 m sebenarnya.",
          kunci: true,
          bahas: "500 cm = 5 m, jadi benar." },
        { tipe: "jodoh", q: "Pasangkan setiap skala pada kolom kiri dengan artinya yang tepat.",
          items: ["1 : 100", "1 : 1.000", "1 : 50"],
          options: ["1 cm = 1 m", "1 cm = 10 m", "1 cm = 50 cm", "1 cm = 100 m"],
          kunci: [0,1,2],
          bahas: "1:100 → 1 cm = 100 cm = 1 m; 1:1.000 → 1 cm = 10 m; 1:50 → 1 cm = 50 cm." },
        { tipe: "jodoh", q: "Pasangkan setiap pengukuran pada kolom kiri dengan jarak sebenarnya yang tepat.",
          items: ["4 cm pada peta 1 : 250", "3 cm pada denah 1 : 100", "10 cm pada peta 1 : 50.000"],
          options: ["3 m", "5 km", "10 m", "1 km"],
          kunci: [2,0,1],
          bahas: "4 × 250 = 1.000 cm = 10 m; 3 × 100 = 300 cm = 3 m; 10 × 50.000 = 500.000 cm = 5 km." },
        { tipe: "isian", q: "Peta berskala 1 : 200.000. Jarak 5 cm pada peta sama dengan .... km sebenarnya.",
          kunci: ["10"],
          bahas: "5 × 200.000 = 1.000.000 cm = 10 km." },
        { tipe: "isian", q: "Dua persegi panjang sebangun. Panjang 12 cm dan lebar 8 cm; panjang yang lain 9 cm. Lebarnya .... cm.",
          kunci: ["6"],
          bahas: "12/9 = 8/l → 12l = 72 → l = 6 cm." }
      ]
    },
    {
      id: "paket-09",
      judul: "Pertidaksamaan Linear Satu Variabel",
      deskripsi: "Garis bilangan, pertidaksamaan, dan soal cerita.",
      soal: [
        { tipe: "pgk", q: "Pernyataan yang benar tentang pertidaksamaan x + 5 > 12 adalah ....",
          options: ["Himpunan penyelesaiannya x > 7", "x = 7 termasuk penyelesaian", "x = 10 memenuhi", "Himpunan penyelesaiannya x < 7"],
          kunci: [0,2],
          bahas: "x > 12 − 5 → x > 7. Jadi x = 10 memenuhi, tetapi x = 7 tidak termasuk penyelesaian." },
        { tipe: "pgk", q: "Pertidaksamaan berikut yang ekuivalen dengan 2x ≥ 10 adalah ....",
          options: ["x ≥ 5", "x ≤ 5", "4x ≥ 20", "x > 5"],
          kunci: [0,2],
          bahas: "2x ≥ 10 → x ≥ 5. Dikalikan 2 menjadi 4x ≥ 20 yang juga ekuivalen." },
        { tipe: "pgk", q: "Bilangan bulat yang memenuhi 2 ≤ x < 6 adalah ....",
          options: ["1", "2", "3", "5"],
          kunci: [1,2,3],
          bahas: "Bilangan bulat dari 2 sampai kurang dari 6 adalah 2, 3, 4, dan 5." },
        { tipe: "bs", q: "Pernyataan: Jika x < 5 maka −x > −5.",
          kunci: true,
          bahas: "Mengalikan kedua ruas dengan −1 membalik tanda: −x > −5." },
        { tipe: "bs", q: "Pernyataan: Himpunan penyelesaian 3x ≤ 12 adalah x ≥ 4.",
          kunci: false,
          bahas: "3x ≤ 12 → x ≤ 4, bukan x ≥ 4." },
        { tipe: "bs", q: "Pernyataan: −2 > −5.",
          kunci: true,
          bahas: "−2 terletak di kanan −5 pada garis bilangan." },
        { tipe: "jodoh", q: "Pasangkan setiap pertidaksamaan pada kolom kiri dengan gambar garis bilangannya yang tepat.",
          items: ["x > 3", "x ≤ −1", "x ≥ 2"],
          options: ["Bulatan penuh di 2, arsir ke kanan", "Bulatan kosong di 3, arsir ke kanan", "Bulatan penuh di −1, arsir ke kiri", "Garis penuh ke semua arah"],
          kunci: [1,2,0],
          bahas: "x > 3: bulatan kosong di 3, arsir ke kanan; x ≤ −1: bulatan penuh di −1, arsir ke kiri; x ≥ 2: bulatan penuh di 2, arsir ke kanan." },
        { tipe: "jodoh", q: "Pasangkan setiap kalimat pada kolom kiri dengan model pertidaksamaannya yang tepat.",
          items: ["Umur minimal 17 tahun untuk membuat SIM", "Tinggi minimal 150 cm untuk wahana", "Nilai minimal 75 untuk lulus"],
          options: ["u ≥ 17", "t ≥ 150", "n ≥ 75", "n > 75"],
          kunci: [0,1,2],
          bahas: "Kata 'minimal' artinya lebih dari atau sama dengan (≥)." },
        { tipe: "isian", q: "Penyelesaian dari 4x − 8 < 16 adalah x < ....",
          kunci: ["6"],
          bahas: "4x < 24 → x < 6." },
        { tipe: "isian", q: "Bilangan bulat terbesar yang memenuhi 2x + 1 ≤ 15 adalah ....",
          kunci: ["7"],
          bahas: "2x ≤ 14 → x ≤ 7, jadi bilangan bulat terbesarnya adalah 7." }
      ]
    },
    {
      id: "paket-10",
      judul: "Pola Bilangan",
      deskripsi: "Menentukan suku barisan aritmetika, beda antar-suku, dan rumus suku ke-n.",
      soal: [
        { tipe: "pgk", q: "Barisan 3, 7, 11, 15, .... Pernyataan yang benar adalah ....",
          options: ["Bedanya 4", "Suku ke-6 adalah 23", "Rumus suku ke-n: Un = 4n − 1", "Suku ke-10 adalah 43"],
          kunci: [0,1,2],
          bahas: "Beda = 4; U6 = 3 + 5×4 = 23; Un = 4n − 1 (U1 = 3). Suku ke-10 = 4(10) − 1 = 39, bukan 43." },
        { tipe: "pgk", q: "Barisan aritmetika dengan U1 = 5 dan beda 3. Pernyataan yang benar adalah ....",
          options: ["U2 = 8", "U5 = 18", "Un = 3n + 2", "U10 = 35"],
          kunci: [0,2],
          bahas: "U2 = 5+3 = 8; Un = 5 + (n−1)×3 = 3n+2. U5 = 17 dan U10 = 32." },
        { tipe: "pgk", q: "Pola bilangan berikut yang merupakan barisan aritmetika adalah ....",
          options: ["2, 4, 8, 16", "5, 9, 13, 17", "1, 4, 9, 16", "20, 17, 14, 11"],
          kunci: [1,3],
          bahas: "5, 9, 13, 17 beda tetap 4 dan 20, 17, 14, 11 beda tetap −3. Pola lainnya bedanya tidak tetap." },
        { tipe: "bs", q: "Pernyataan: Beda barisan 10, 7, 4, 1 adalah 3.",
          kunci: false,
          bahas: "Bedanya 7 − 10 = −3, bukan 3." },
        { tipe: "bs", q: "Pernyataan: Suku ke-4 barisan 2, 5, 8, 11 adalah 11.",
          kunci: true,
          bahas: "U4 = 2 + 3×3 = 11." },
        { tipe: "bs", q: "Pernyataan: Rumus suku ke-n barisan 6, 10, 14, 18 adalah Un = 4n + 2.",
          kunci: true,
          bahas: "U1 = 4(1)+2 = 6 dan bedanya 4, sesuai dengan barisan." },
        { tipe: "jodoh", q: "Pasangkan setiap barisan pada kolom kiri dengan bedanya yang tepat.",
          items: ["2, 6, 10, 14", "15, 11, 7, 3", "9, 9, 9, 9"],
          options: ["4", "−4", "0", "2"],
          kunci: [0,1,2],
          bahas: "Bedanya berturut-turut 4, −4, dan 0." },
        { tipe: "jodoh", q: "Pasangkan setiap rumus suku ke-n pada kolom kiri dengan nilai suku yang diminta.",
          items: ["Un = 2n + 1, nilai U5", "Un = 5n − 2, nilai U4", "Un = 10 − n, nilai U3"],
          options: ["18", "7", "11", "9"],
          kunci: [2,0,1],
          bahas: "U5 = 2(5)+1 = 11; U4 = 5(4)−2 = 18; U3 = 10−3 = 7." },
        { tipe: "isian", q: "Suku ke-20 dari barisan 4, 9, 14, 19 adalah ....",
          kunci: ["99"],
          bahas: "Un = 5n − 1, sehingga U20 = 5(20) − 1 = 99." },
        { tipe: "isian", q: "Beda barisan aritmetika 25, 21, 17, 13 adalah ....",
          kunci: ["-4"],
          bahas: "21 − 25 = −4." }
      ]
    },
    {
      id: "paket-11",
      judul: "Rasio",
      deskripsi: "Skala peta, perbandingan senilai, dan perbandingan berbalik nilai.",
      soal: [
        { tipe: "pgk", q: "Perbandingan kelereng Andi : Budi = 3 : 5 dan jumlahnya 40. Pernyataan yang benar adalah ....",
          options: ["Kelereng Andi 15", "Kelereng Budi 25", "Selisih keduanya 8", "Perbandingannya senilai dengan 6 : 10"],
          kunci: [0,1,3],
          bahas: "Andi = 3/8 × 40 = 15; Budi = 5/8 × 40 = 25; selisih = 10. Perbandingan 3:5 = 6:10." },
        { tipe: "pgk", q: "6 pekerja menyelesaikan pekerjaan dalam 12 hari. Jika pekerjanya 9 orang dengan kecepatan sama, pernyataan yang benar adalah ....",
          options: ["Termasuk perbandingan berbalik nilai", "Selesai dalam 18 hari", "Selesai dalam 8 hari", "Termasuk perbandingan senilai"],
          kunci: [0,2],
          bahas: "Pekerja × hari tetap: 6 × 12 = 9 × d → d = 8 hari. Ini perbandingan berbalik nilai." },
        { tipe: "pgk", q: "Harga 4 kg beras Rp48.000,00. Pernyataan yang benar adalah ....",
          options: ["Harga 1 kg Rp12.000,00", "Termasuk perbandingan senilai", "Harga 7 kg Rp80.000,00", "Harga 10 kg Rp120.000,00"],
          kunci: [0,1,3],
          bahas: "Harga per kg = 12.000 (senilai). 7 kg = 84.000 dan 10 kg = 120.000." },
        { tipe: "bs", q: "Pernyataan: 2 : 3 senilai dengan 8 : 12.",
          kunci: true,
          bahas: "2/3 = 8/12 setelah pembilang dan penyebut dikalikan 4." },
        { tipe: "bs", q: "Pernyataan: Jika 3 buku Rp9.000,00 maka 5 buku Rp12.000,00.",
          kunci: false,
          bahas: "Harga per buku 3.000, jadi 5 buku = 15.000." },
        { tipe: "bs", q: "Pernyataan: Makin banyak pekerja, pekerjaan makin cepat selesai (berbalik nilai).",
          kunci: true,
          bahas: "Hasil kali pekerja × waktu tetap, jadi berbalik nilai." },
        { tipe: "jodoh", q: "Pasangkan setiap perbandingan pada kolom kiri dengan bentuk sederhananya yang tepat.",
          items: ["6 : 9", "10 : 25", "4 : 12"],
          options: ["2 : 3", "2 : 5", "1 : 3", "3 : 2"],
          kunci: [0,1,2],
          bahas: "6:9 = 2:3; 10:25 = 2:5; 4:12 = 1:3." },
        { tipe: "jodoh", q: "Pasangkan setiap perbandingan senilai pada kolom kiri dengan nilai yang tepat.",
          items: ["Nilai x dari 2 : 5 = 6 : x", "Nilai y dari 3 : 4 = 9 : y", "Nilai z dari 5 : 7 = 20 : z"],
          options: ["12", "28", "15", "20"],
          kunci: [2,0,1],
          bahas: "x = 6×5/2 = 15; y = 9×4/3 = 12; z = 20×7/5 = 28." },
        { tipe: "isian", q: "Skala peta 1 : 300.000. Jarak 4 cm pada peta sama dengan .... km sebenarnya.",
          kunci: ["12"],
          bahas: "4 × 300.000 = 1.200.000 cm = 12 km." },
        { tipe: "isian", q: "Persediaan pakan untuk 20 ayam habis dalam 15 hari. Untuk 25 ayam akan habis dalam .... hari.",
          kunci: ["12"],
          bahas: "Berbalik nilai: 20 × 15 = 25 × d → d = 12." }
      ]
    },
    {
      id: "paket-12",
      judul: "Segitiga dan Segiempat",
      deskripsi: "Menghitung keliling dan luas persegi, persegi panjang, trapesium, dan segitiga.",
      soal: [
        { tipe: "pgk", q: "Persegi dengan sisi 8 cm. Pernyataan yang benar adalah ....",
          options: ["Keliling = 32 cm", "Luas = 64 cm²", "Diagonal = 8√2 cm", "Luas = 32 cm²"],
          kunci: [0,1,2],
          bahas: "Keliling = 4×8 = 32; luas = 8² = 64; diagonal = 8√2." },
        { tipe: "pgk", q: "Segitiga dengan alas 10 cm dan tinggi 6 cm. Pernyataan yang benar adalah ....",
          options: ["Luas = 30 cm²", "Jika alasnya 2 kali, luasnya 2 kali", "Luas = 60 cm²", "Kelilingnya pasti 16 cm"],
          kunci: [0,1],
          bahas: "Luas = ½×10×6 = 30. Luas sebanding dengan alas. Keliling tidak bisa ditentukan dari data ini." },
        { tipe: "pgk", q: "Trapesium dengan sisi sejajar 8 cm dan 12 cm serta tinggi 5 cm. Pernyataan yang benar adalah ....",
          options: ["Luas = 50 cm²", "Rumusnya ½ × jumlah sisi sejajar × tinggi", "Luas = 100 cm²", "Jika tingginya 10 cm, luasnya 100 cm²"],
          kunci: [0,1,3],
          bahas: "Luas = ½×(8+12)×5 = 50. Jika tinggi 10: ½×20×10 = 100." },
        { tipe: "bs", q: "Pernyataan: Keliling persegi panjang dengan p = 10 cm dan l = 6 cm adalah 32 cm.",
          kunci: true,
          bahas: "K = 2(10+6) = 32." },
        { tipe: "bs", q: "Pernyataan: Luas segitiga = alas × tinggi.",
          kunci: false,
          bahas: "Rumus yang benar adalah ½ × alas × tinggi." },
        { tipe: "bs", q: "Pernyataan: Persegi adalah belah ketupat yang semua sudutnya siku-siku.",
          kunci: true,
          bahas: "Persegi memenuhi sifat belah ketupat dengan sudut 90°." },
        { tipe: "jodoh", q: "Pasangkan setiap bangun datar pada kolom kiri dengan rumus luasnya yang tepat.",
          items: ["Persegi dengan sisi s", "Persegi panjang", "Segitiga"],
          options: ["p × l", "½ × a × t", "s²", "a × t"],
          kunci: [2,0,1],
          bahas: "Persegi: s²; persegi panjang: p×l; segitiga: ½×a×t." },
        { tipe: "jodoh", q: "Pasangkan setiap bangun pada kolom kiri dengan luasnya yang tepat.",
          items: ["Persegi dengan s = 9 cm", "Persegi panjang p = 12 cm, l = 7 cm", "Segitiga a = 8 cm, t = 5 cm"],
          options: ["81 cm²", "84 cm²", "20 cm²", "40 cm²"],
          kunci: [0,1,2],
          bahas: "9² = 81; 12×7 = 84; ½×8×5 = 20." },
        { tipe: "isian", q: "Keliling sebuah persegi 48 cm. Luasnya .... cm².",
          kunci: ["144"],
          bahas: "s = 48 ÷ 4 = 12, luas = 12² = 144." },
        { tipe: "isian", q: "Luas jajargenjang 96 cm² dengan alas 12 cm. Tingginya .... cm.",
          kunci: ["8"],
          bahas: "t = 96 ÷ 12 = 8." }
      ]
    }
  ]
};
