window.BANK_KELAS_8 = {
  info: { kelas: "8", label: "Kelas 8" },
  paket: [
    {
      id: "paket-01",
      judul: "Bilangan Berpangkat",
      deskripsi: "Konsep eksponen, sifat-sifat operasi bilangan berpangkat positif, negatif, dan nol.",
      soal: [
        { tipe: "pgk", q: "Manakah pernyataan berikut yang BENAR tentang bilangan berpangkat?",
          options: ["2³ × 2⁴ = 2⁷", "(3²)³ = 3⁶", "5² + 5³ = 5⁵", "4⁰ = 1"],
          kunci: [0, 1, 3],
          bahas: "2³×2⁴ = 2⁷ (128) dan (3²)³ = 3⁶ (729) benar. 4⁰ = 1 benar. Namun 5²+5³ = 25+125 = 150, bukan 5⁵ = 3125." },
        { tipe: "pgk", q: "Pilih semua bentuk yang nilainya sama dengan 64.",
          options: ["2⁶", "8²", "4³", "2³ × 2²"],
          kunci: [0, 1, 2],
          bahas: "2⁶ = 64, 8² = 64, dan 4³ = 64. Sedangkan 2³ × 2² = 2⁵ = 32, bukan 64." },
        { tipe: "pgk", q: "Pilih semua bentuk yang senilai dengan 3⁻².",
          options: ["−9", "1/9", "(1/3)²", "1/3²"],
          kunci: [1, 2, 3],
          bahas: "3⁻² = 1/3² = 1/9, dan (1/3)² = 1/9 juga. −9 bukan bentuk pangkat negatif, melainkan bilangan negatif biasa." },
        { tipe: "bs", q: "Pernyataan: (−2)⁴ = −16",
          kunci: false,
          bahas: "Salah. (−2)⁴ = (−2)×(−2)×(−2)×(−2) = 16, karena pangkat genap menghasilkan bilangan positif." },
        { tipe: "bs", q: "Pernyataan: (2/3)⁻¹ = 3/2",
          kunci: true,
          bahas: "Benar. Pangkat negatif satu berarti kebalikan (resiprokal): (2/3)⁻¹ = 3/2." },
        { tipe: "bs", q: "Pernyataan: a⁻ⁿ = −aⁿ untuk setiap a ≠ 0",
          kunci: false,
          bahas: "Salah. Pangkat negatif berarti kebalikan: a⁻ⁿ = 1/aⁿ, bukan bilangan negatif −aⁿ." },
        { tipe: "jodoh", q: "Pasangkan setiap bentuk dengan nilai yang tepat.",
          items: ["5² × 5⁻¹", "(2³)²", "10³ ÷ 10²"],
          options: ["5", "64", "10", "25"],
          kunci: [0, 1, 2],
          bahas: "5²×5⁻¹ = 5¹ = 5; (2³)² = 2⁶ = 64; 10³÷10² = 10¹ = 10." },
        { tipe: "jodoh", q: "Pasangkan setiap bentuk pangkat negatif dengan pecahan yang senilai.",
          items: ["2⁻²", "3⁻¹", "5⁻³"],
          options: ["1/4", "1/3", "1/125", "1/25"],
          kunci: [0, 1, 2],
          bahas: "2⁻² = 1/2² = 1/4; 3⁻¹ = 1/3; 5⁻³ = 1/5³ = 1/125." },
        { tipe: "isian", q: "Nilai dari 3⁴ − 2⁵ adalah ....",
          kunci: ["49"],
          bahas: "3⁴ = 81 dan 2⁵ = 32, sehingga 81 − 32 = 49." },
        { tipe: "isian", q: "Nilai x yang memenuhi 2ˣ = 128 adalah x = ....",
          kunci: ["7"],
          bahas: "Karena 2⁷ = 128, maka x = 7." }
      ]
    },
    {
      id: "paket-02",
      judul: "Bentuk Akar",
      deskripsi: "Menyederhanakan bentuk akar, operasi aritmetika, dan merasionalkan penyebut pecahan.",
      soal: [
        { tipe: "pgk", q: "Pilih semua bentuk yang nilainya sama dengan √72.",
          options: ["6√2", "√36 × √2", "√144 ÷ √2", "9√2"],
          kunci: [0, 1, 2],
          bahas: "√72 = 6√2. √36×√2 = 6√2 dan √144÷√2 = √(144/2) = √72. Sedangkan 9√2 = √162." },
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR tentang operasi bentuk akar.",
          options: ["√a × √b = √(ab)", "√a + √b = √(a+b)", "3√5 + 2√5 = 5√5", "(√3)² = 3"],
          kunci: [0, 2, 3],
          bahas: "Perkalian akar dapat digabung dan bentuk sejenis dapat dijumlahkan. Penjumlahan tidak berlaku √(a+b) = √a+√b." },
        { tipe: "pgk", q: "Hasil dari √50 − √18 + √8 adalah .... Pilih semua bentuk yang tepat.",
          options: ["√16", "4√2", "√32", "2√8"],
          kunci: [1, 2, 3],
          bahas: "√50−√18+√8 = 5√2−3√2+2√2 = 4√2. Bentuk lain: √32 = 4√2 dan 2√8 = 4√2. √16 = 4, salah." },
        { tipe: "bs", q: "Pernyataan: √25 + √16 = √41",
          kunci: false,
          bahas: "Salah. √25+√16 = 5+4 = 9, sedangkan √41 ≈ 6,4. Akar tidak dapat dijumlahkan langsung seperti itu." },
        { tipe: "bs", q: "Pernyataan: (5√2)² = 50",
          kunci: true,
          bahas: "Benar. (5√2)² = 25 × 2 = 50." },
        { tipe: "bs", q: "Pernyataan: √48 = 4√3",
          kunci: true,
          bahas: "Benar. √48 = √(16×3) = 4√3." },
        { tipe: "jodoh", q: "Pasangkan setiap bentuk akar dengan bentuk sederhananya.",
          items: ["√75", "√98", "√125"],
          options: ["5√3", "7√2", "5√5", "3√5"],
          kunci: [0, 1, 2],
          bahas: "√75 = 5√3; √98 = 7√2; √125 = 5√5." },
        { tipe: "jodoh", q: "Pasangkan setiap pecahan dengan bentuk rasionalnya (penyebut dirasionalkan).",
          items: ["4/√2", "3/√3", "5/(2√5)"],
          options: ["2√2", "√3", "√5/2", "5√5/2"],
          kunci: [0, 1, 2],
          bahas: "4/√2 = 2√2; 3/√3 = √3; 5/(2√5) = 5√5/10 = √5/2." },
        { tipe: "isian", q: "Hasil dari 2√3 + 5√3 − 4√3 adalah ....",
          kunci: ["3√3"],
          bahas: "Koefisiennya: 2+5−4 = 3, jadi hasilnya 3√3." },
        { tipe: "isian", q: "Nilai dari √144 − √81 adalah ....",
          kunci: ["3"],
          bahas: "√144 = 12 dan √81 = 9, sehingga 12 − 9 = 3." }
      ]
    },
    {
      id: "paket-03",
      judul: "Bentuk Baku",
      deskripsi: "Menuliskan bilangan sangat besar atau sangat kecil dalam notasi ilmiah.",
      soal: [
        { tipe: "pgk", q: "Pilih semua penulisan bentuk baku (notasi ilmiah a × 10ⁿ, dengan 1 ≤ a < 10) yang BENAR.",
          options: ["3,5 × 10⁶", "35 × 10⁵", "7,2 × 10⁻⁴", "0,9 × 10³"],
          kunci: [0, 2],
          bahas: "Syarat bentuk baku: 1 ≤ a < 10. 35 × 10⁵ salah (a = 35) dan 0,9 × 10³ salah (a = 0,9)." },
        { tipe: "pgk", q: "Pilih semua bilangan yang nilainya sama dengan 4,2 × 10⁵.",
          options: ["420.000", "42 × 10⁴", "0,42 × 10⁶", "4.200.000"],
          kunci: [0, 1, 2],
          bahas: "4,2×10⁵ = 420.000. 42×10⁴ = 420.000 dan 0,42×10⁶ = 420.000 juga. 4.200.000 = 4,2×10⁶, salah." },
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR.",
          options: ["1 cm = 1 × 10⁻¹ m", "1 km = 1 × 10³ m", "1 mm = 1 × 10⁻³ m", "1 kg = 1 × 10³ g"],
          kunci: [1, 2, 3],
          bahas: "1 km = 1000 m, 1 mm = 0,001 m, 1 kg = 1000 g benar. 1 cm = 10⁻² m, bukan 10⁻¹ m." },
        { tipe: "bs", q: "Pernyataan: 0,000025 = 2,5 × 10⁻⁵",
          kunci: true,
          bahas: "Benar. Koma bergeser 5 tempat ke kanan: 0,000025 = 2,5 × 10⁻⁵." },
        { tipe: "bs", q: "Pernyataan: 9,8 × 10⁷ = 98.000.000",
          kunci: true,
          bahas: "Benar. 9,8 × 10.000.000 = 98.000.000." },
        { tipe: "bs", q: "Pernyataan: Bentuk baku dari 50.000 adalah 5 × 10⁵",
          kunci: false,
          bahas: "Salah. 50.000 = 5 × 10⁴, bukan 5 × 10⁵ (= 500.000)." },
        { tipe: "jodoh", q: "Pasangkan setiap bilangan dengan bentuk bakunya.",
          items: ["72.000.000", "0,00000043", "5.600"],
          options: ["7,2 × 10⁷", "4,3 × 10⁻⁷", "5,6 × 10³", "7,2 × 10⁶"],
          kunci: [0, 1, 2],
          bahas: "72.000.000 = 7,2×10⁷; 0,00000043 = 4,3×10⁻⁷; 5.600 = 5,6×10³." },
        { tipe: "jodoh", q: "Pasangkan setiap bentuk baku dengan nilai bilangannya.",
          items: ["2,5 × 10⁴", "6 × 10⁻³", "1,2 × 10²"],
          options: ["25.000", "0,006", "120", "250.000"],
          kunci: [0, 1, 2],
          bahas: "2,5×10⁴ = 25.000; 6×10⁻³ = 0,006; 1,2×10² = 120." },
        { tipe: "isian", q: "Bentuk baku dari 0,000036 adalah ....",
          kunci: ["3,6 × 10⁻⁵", "3,6×10⁻⁵", "3.6 × 10^-5"],
          bahas: "Koma bergeser 5 tempat ke kanan sehingga 0,000036 = 3,6 × 10⁻⁵." },
        { tipe: "isian", q: "Nilai dari (2 × 10³) × (3 × 10²) dalam bentuk baku adalah ....",
          kunci: ["6 × 10⁵", "6×10⁵"],
          bahas: "(2×3) × 10³⁺² = 6 × 10⁵." }
      ]
    },
    {
      id: "paket-04",
      judul: "Relasi dan Fungsi",
      deskripsi: "Membedakan relasi dan fungsi, diagram panah/koordinat, serta menghitung nilai fungsi.",
      soal: [
        { tipe: "pgk", q: "Diketahui A = {1, 2, 3} dan B = {a, b}. Manakah yang merupakan fungsi dari A ke B?",
          options: ["{(1,a), (2,b)}", "{(1,a), (2,a), (3,b)}", "{(1,a), (1,b), (2,a), (3,b)}", "{(1,a), (2,a), (3,a)}"],
          kunci: [1, 3],
          bahas: "Fungsi memasangkan setiap anggota domain tepat satu kali. Himpunan kedua tidak memetakan 3, himpunan ketiga memetakan 1 dua kali." },
        { tipe: "pgk", q: "Diketahui fungsi f(x) = 2x − 5. Pilih semua pernyataan yang BENAR.",
          options: ["Nilai f(10) adalah 10", "f(0) = −5", "f(3) = 1", "f(−2) = −9"],
          kunci: [1, 2, 3],
          bahas: "f(0) = −5, f(3) = 6−5 = 1, f(−2) = −4−5 = −9. f(10) = 15, bukan 10." },
        { tipe: "pgk", q: "Pilih semua yang merupakan ciri-ciri fungsi.",
          options: ["Setiap anggota domain tepat berpasangan dengan satu anggota kodomain", "Setiap anggota kodomain harus memiliki pasangan", "Dapat dinyatakan dengan diagram panah, himpunan pasangan berurutan, atau grafik", "Relasi yang memasangkan setiap anggota domain tepat satu kali"],
          kunci: [0, 2, 3],
          bahas: "Ciri fungsi: setiap anggota domain berpasangan tepat satu kali. Anggota kodomain tidak wajib semuanya memiliki pasangan." },
        { tipe: "bs", q: "Pernyataan: Relasi 'faktor dari' dari {2, 3} ke {4, 6, 9} merupakan fungsi",
          kunci: false,
          bahas: "Salah. 2 berpasangan dengan 4 dan 6, sedangkan 3 berpasangan dengan 6 dan 9 — satu anggota domain punya lebih dari satu pasangan." },
        { tipe: "bs", q: "Pernyataan: Jika g(x) = x² + 1 maka g(−3) = 10",
          kunci: true,
          bahas: "Benar. g(−3) = (−3)² + 1 = 9 + 1 = 10." },
        { tipe: "bs", q: "Pernyataan: Himpunan pasangan berurutan {(a,1), (b,2), (c,2)} merupakan fungsi",
          kunci: true,
          bahas: "Benar. Setiap anggota domain (a, b, c) muncul tepat satu kali, walaupun b dan c sama-sama berpasangan dengan 2." },
        { tipe: "jodoh", q: "Diketahui f(x) = 3x + 2. Pasangkan setiap nilai x dengan nilai f(x).",
          items: ["x = 0", "x = 2", "x = −1"],
          options: ["2", "8", "−1", "5"],
          kunci: [0, 1, 2],
          bahas: "f(0) = 2; f(2) = 8; f(−1) = −3+2 = −1." },
        { tipe: "jodoh", q: "Pasangkan setiap himpunan pasangan berurutan dengan domainnya.",
          items: ["{(2,a), (4,b), (6,c)}", "{(1,x), (3,y), (5,z)}", "{(0,p), (7,q), (9,r)}"],
          options: ["{2, 4, 6}", "{1, 3, 5}", "{0, 7, 9}", "{a, b, c}"],
          kunci: [0, 1, 2],
          bahas: "Domain adalah himpunan semua anggota pertama: {2,4,6}, {1,3,5}, {0,7,9}." },
        { tipe: "isian", q: "Diketahui h(x) = 5x − 3. Nilai h(4) adalah ....",
          kunci: ["17"],
          bahas: "h(4) = 5×4 − 3 = 20 − 3 = 17." },
        { tipe: "isian", q: "Banyaknya pemetaan (fungsi) dari A = {p, q} ke B = {1, 2, 3} adalah ....",
          kunci: ["9"],
          bahas: "Banyak fungsi dari A ke B = n(B)ⁿ⁽ᴬ⁾ = 3² = 9." }
      ]
    },
    {
      id: "paket-05",
      judul: "Persamaan Garis Lurus",
      deskripsi: "Gradien, grafik garis lurus, dan menyusun persamaan garis.",
      soal: [
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR tentang gradien.",
          options: ["Gradien garis y = 3x + 2 adalah 3", "Gradien garis yang melalui (0, 0) dan (2, 6) adalah 3", "Garis vertikal x = 4 memiliki gradien 0", "Garis horizontal memiliki gradien 0"],
          kunci: [0, 1, 3],
          bahas: "Gradien y = 3x+2 adalah 3; (6−0)/(2−0) = 3; garis horizontal gradiennya 0. Garis vertikal gradiennya tak terdefinisi, bukan 0." },
        { tipe: "pgk", q: "Pilih semua persamaan garis yang memiliki gradien 2.",
          options: ["y = 2x − 5", "2y = 4x + 6", "y − 2x = 7", "x + 2y = 8"],
          kunci: [0, 1, 2],
          bahas: "y = 2x−5 (m=2); 2y = 4x+6 → y = 2x+3 (m=2); y−2x = 7 → y = 2x+7 (m=2). x+2y = 8 → y = −½x+4 (m=−½)." },
        { tipe: "pgk", q: "Garis k melalui titik (1, 3) dan (5, 11). Pilih semua pernyataan yang BENAR.",
          options: ["Garis k sejajar dengan garis y = −2x + 5", "Gradien garis k adalah 2", "Persamaan garis k adalah y = 2x + 1", "Titik (0, 1) terletak pada garis k"],
          kunci: [1, 2, 3],
          bahas: "m = (11−3)/(5−1) = 2, persamaan y = 2x+1. Titik (0,1): 2(0)+1 = 1, terletak pada garis. Tidak sejajar y = −2x+5 karena gradiennya −2." },
        { tipe: "bs", q: "Pernyataan: Titik (2, 5) terletak pada garis y = 3x − 1",
          kunci: true,
          bahas: "Benar. 3(2) − 1 = 5, sesuai dengan ordinat titik." },
        { tipe: "bs", q: "Pernyataan: Gradien garis 3x + y = 9 adalah 3",
          kunci: false,
          bahas: "Salah. 3x+y = 9 → y = −3x+9, gradiennya −3." },
        { tipe: "bs", q: "Pernyataan: Garis y = 2x + 1 dan y = 2x − 4 saling sejajar",
          kunci: true,
          bahas: "Benar. Kedua garis memiliki gradien yang sama, yaitu 2, sehingga sejajar." },
        { tipe: "jodoh", q: "Pasangkan setiap persamaan garis dengan gradiennya.",
          items: ["y = −4x + 3", "2x − y = 5", "x + 3y = 6"],
          options: ["−4", "2", "−1/3", "3"],
          kunci: [0, 1, 2],
          bahas: "y = −4x+3 → m = −4; 2x−y = 5 → y = 2x−5, m = 2; x+3y = 6 → y = −⅓x+2, m = −1/3." },
        { tipe: "jodoh", q: "Pasangkan setiap garis dengan titik yang dilaluinya.",
          items: ["y = x + 2", "y = 2x − 3", "y = −x + 5"],
          options: ["(1, 3)", "(2, 1)", "(3, 2)", "(4, 0)"],
          kunci: [0, 1, 2],
          bahas: "(1,3): 1+2 = 3; (2,1): 4−3 = 1; (3,2): −3+5 = 2. Titik (4,0) tidak terletak pada garis mana pun." },
        { tipe: "isian", q: "Gradien garis yang melalui titik (−2, 4) dan (3, −6) adalah ....",
          kunci: ["−2", "-2"],
          bahas: "m = (−6−4)/(3−(−2)) = −10/5 = −2." },
        { tipe: "isian", q: "Persamaan garis yang melalui (0, −3) dengan gradien 4 adalah y = ....",
          kunci: ["4x − 3", "4x-3"],
          bahas: "Bentuk y = mx + c dengan m = 4 dan c = −3, jadi y = 4x − 3." }
      ]
    },
    {
      id: "paket-06",
      judul: "SPLDV",
      deskripsi: "Metode eliminasi, substitusi, dan grafik untuk sistem persamaan linear dua variabel.",
      soal: [
        { tipe: "pgk", q: "Diketahui SPLDV: 2x + y = 7 dan x − y = 2. Pilih semua pernyataan yang BENAR.",
          options: ["Nilai x = 3", "Nilai y = 1", "Himpunan penyelesaiannya {(3, 1)}", "Nilai x + y = 5"],
          kunci: [0, 1, 2],
          bahas: "Jumlahkan kedua persamaan: 3x = 9 → x = 3, lalu y = 7−6 = 1. Jadi x+y = 4, bukan 5." },
        { tipe: "pgk", q: "Pilih semua pasangan (x, y) yang merupakan penyelesaian dari x + 2y = 8.",
          options: ["(6, 2)", "(2, 3)", "(4, 2)", "(0, 4)"],
          kunci: [1, 2, 3],
          bahas: "(2,3): 2+6 = 8; (4,2): 4+4 = 8; (0,4): 0+8 = 8. (6,2): 6+4 = 10 ≠ 8." },
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR tentang metode penyelesaian SPLDV.",
          options: ["Eliminasi menghilangkan salah satu variabel dengan menjumlahkan/mengurangkan persamaan", "Substitusi mengganti satu variabel dengan ekspresi dari persamaan lain", "SPLDV selalu memiliki tepat satu penyelesaian", "Penyelesaian SPLDV dapat ditentukan dengan menggambar grafik kedua garis"],
          kunci: [0, 1, 3],
          bahas: "Eliminasi, substitusi, dan grafik adalah metode yang sah. SPLDV tidak selalu punya tepat satu penyelesaian — bisa tak berhingga atau tidak ada." },
        { tipe: "bs", q: "Pernyataan: Penyelesaian dari x + y = 5 dan x − y = 1 adalah x = 3 dan y = 2",
          kunci: true,
          bahas: "Benar. Jumlahkan: 2x = 6 → x = 3, lalu y = 5−3 = 2." },
        { tipe: "bs", q: "Pernyataan: Sistem x + y = 4 dan 2x + 2y = 8 tidak memiliki penyelesaian",
          kunci: false,
          bahas: "Salah. Persamaan kedua adalah dua kali persamaan pertama, sehingga sistem memiliki tak berhingga penyelesaian." },
        { tipe: "bs", q: "Pernyataan: Jika 3x + 2y = 12 dan x = 2, maka y = 3",
          kunci: true,
          bahas: "Benar. 3(2)+2y = 12 → 2y = 6 → y = 3." },
        { tipe: "jodoh", q: "Pasangkan setiap SPLDV dengan himpunan penyelesaiannya.",
          items: ["x + y = 6; x − y = 2", "2x + y = 10; x + y = 7", "x + 3y = 11; x + y = 5"],
          options: ["{(4, 2)}", "{(3, 4)}", "{(2, 3)}", "{(5, 1)}"],
          kunci: [0, 1, 2],
          bahas: "x=4,y=2; x=3,y=4; dan dari 2y = 6 diperoleh y=3, x=2." },
        { tipe: "jodoh", q: "Harga 2 buku dan 1 pensil Rp7.000,00; harga 1 buku dan 1 pensil Rp4.500,00. Pasangkan setiap barang dengan harganya.",
          items: ["1 buku", "1 pensil", "1 buku + 1 pensil"],
          options: ["Rp2.500,00", "Rp2.000,00", "Rp4.500,00", "Rp3.000,00"],
          kunci: [0, 1, 2],
          bahas: "Kurangkan: (2b+p)−(b+p) = 7000−4500 → b = 2500, lalu p = 4500−2500 = 2000." },
        { tipe: "isian", q: "Nilai y yang memenuhi 4x − y = 5 dan 2x + y = 7 adalah y = ....",
          kunci: ["3"],
          bahas: "Jumlahkan: 6x = 12 → x = 2, lalu 8−y = 5 → y = 3." },
        { tipe: "isian", q: "Jumlah dua bilangan adalah 15 dan selisihnya 3. Bilangan yang lebih besar adalah ....",
          kunci: ["9"],
          bahas: "Bilangan besar = (15+3)/2 = 9; yang kecil 6." }
      ]
    },
    {
      id: "paket-07",
      judul: "Teorema Pythagoras",
      deskripsi: "Rumus a² + b² = c², tripel Pythagoras, dan jarak antar titik.",
      soal: [
        { tipe: "pgk", q: "Pilih semua yang merupakan tripel Pythagoras.",
          options: ["(3, 4, 5)", "(5, 12, 13)", "(6, 8, 10)", "(4, 5, 6)"],
          kunci: [0, 1, 2],
          bahas: "3²+4² = 5²; 5²+12² = 13²; 6²+8² = 10². Sedangkan 4²+5² = 41 ≠ 36 = 6²." },
        { tipe: "pgk", q: "Segitiga siku-siku memiliki sisi tegak 9 cm dan 12 cm. Pilih semua pernyataan yang BENAR.",
          options: ["Sisi miringnya √63 cm", "Sisi miringnya 15 cm", "Kelilingnya 36 cm", "Luasnya 54 cm²"],
          kunci: [1, 2, 3],
          bahas: "Sisi miring = √(81+144) = 15 cm. Keliling = 9+12+15 = 36 cm. Luas = ½×9×12 = 54 cm²." },
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR tentang teorema Pythagoras.",
          options: ["Berlaku pada segitiga siku-siku: c² = a² + b² dengan c sisi miring", "Dapat digunakan untuk menentukan jarak dua titik pada bidang koordinat", "Berlaku untuk semua jenis segitiga", "Jika a² + b² = c² maka segitiga tersebut siku-siku"],
          kunci: [0, 1, 3],
          bahas: "Teorema Pythagoras hanya berlaku pada segitiga siku-siku, tetapi kebalikannya juga benar: jika a²+b² = c² maka segitiga itu siku-siku." },
        { tipe: "bs", q: "Pernyataan: Panjang sisi miring segitiga dengan sisi tegak 5 cm dan 12 cm adalah 13 cm",
          kunci: true,
          bahas: "Benar. √(5²+12²) = √169 = 13 cm." },
        { tipe: "bs", q: "Pernyataan: Segitiga dengan sisi 7 cm, 24 cm, dan 25 cm merupakan segitiga siku-siku",
          kunci: true,
          bahas: "Benar. 7²+24² = 49+576 = 625 = 25², memenuhi teorema Pythagoras." },
        { tipe: "bs", q: "Pernyataan: Jika sisi miring 10 cm dan satu sisi tegak 6 cm, maka sisi tegak lainnya 7 cm",
          kunci: false,
          bahas: "Salah. Sisi tegak lainnya = √(10²−6²) = √64 = 8 cm, bukan 7 cm." },
        { tipe: "jodoh", q: "Pasangkan setiap pasangan sisi tegak dengan panjang sisi miringnya.",
          items: ["6 cm dan 8 cm", "5 cm dan 12 cm", "8 cm dan 15 cm"],
          options: ["10 cm", "13 cm", "17 cm", "12 cm"],
          kunci: [0, 1, 2],
          bahas: "√(36+64) = 10; √(25+144) = 13; √(64+225) = √289 = 17." },
        { tipe: "jodoh", q: "Pasangkan setiap ukuran segitiga dengan jenisnya.",
          items: ["3 cm, 4 cm, 5 cm", "5 cm, 5 cm, 5 cm", "4 cm, 6 cm, 8 cm"],
          options: ["Siku-siku", "Sama sisi", "Tumpul", "Lancip"],
          kunci: [0, 1, 2],
          bahas: "(3,4,5) siku-siku; (5,5,5) sama sisi; (4,6,8): 4²+6² = 52 < 64 = 8² sehingga tumpul." },
        { tipe: "isian", q: "Panjang diagonal persegi dengan sisi 7 cm adalah .... cm",
          kunci: ["7√2"],
          bahas: "Diagonal = √(7²+7²) = √98 = 7√2 cm." },
        { tipe: "isian", q: "Jarak antara titik A(1, 2) dan B(4, 6) adalah .... satuan",
          kunci: ["5"],
          bahas: "Jarak = √((4−1)²+(6−2)²) = √(9+16) = 5 satuan." }
      ]
    },
    {
      id: "paket-08",
      judul: "Statistika",
      deskripsi: "Mean, median, modus, serta ukuran penyebaran data sederhana.",
      soal: [
        { tipe: "pgk", q: "Data: 5, 7, 7, 8, 8, 8, 9. Pilih semua pernyataan yang BENAR.",
          options: ["Modusnya 8", "Mediannya 8", "Mean-nya 7,5", "Jangkauannya 4"],
          kunci: [0, 1, 3],
          bahas: "Modus = 8 (paling sering), median = 8 (data ke-4 dari 7), jangkauan = 9−5 = 4. Mean = 52/7 ≈ 7,43, bukan 7,5." },
        { tipe: "pgk", q: "Pilih semua pernyataan yang BENAR tentang ukuran pemusatan data.",
          options: ["Mean selalu sama dengan median", "Median adalah nilai tengah setelah data diurutkan", "Modus adalah data yang paling sering muncul", "Data dapat memiliki lebih dari satu modus"],
          kunci: [1, 2, 3],
          bahas: "Mean tidak selalu sama dengan median. Data dapat memiliki lebih dari satu modus (multimodus)." },
        { tipe: "pgk", q: "Nilai ulangan 10 siswa: 6, 7, 8, 6, 9, 7, 8, 8, 7, 6. Pilih semua pernyataan yang BENAR.",
          options: ["Mean-nya 7,2", "Mediannya 7", "Modusnya 8", "Data 9 muncul 1 kali"],
          kunci: [0, 1, 3],
          bahas: "Jumlah = 72, mean = 7,2. Data terurut mediannya (7+7)/2 = 7. Nilai 6, 7, 8 masing-masing muncul 3 kali (tiga modus), 9 muncul 1 kali." },
        { tipe: "bs", q: "Pernyataan: Median dari 4, 6, 5, 9, 7 adalah 6",
          kunci: true,
          bahas: "Benar. Setelah diurutkan 4, 5, 6, 7, 9, nilai tengahnya 6." },
        { tipe: "bs", q: "Pernyataan: Rata-rata dari 10, 20, 30 adalah 25",
          kunci: false,
          bahas: "Salah. (10+20+30)/3 = 60/3 = 20, bukan 25." },
        { tipe: "bs", q: "Pernyataan: Modus dari 2, 3, 3, 4, 4, 4 adalah 4",
          kunci: true,
          bahas: "Benar. Angka 4 muncul 3 kali, paling sering di antara data lainnya." },
        { tipe: "jodoh", q: "Pasangkan setiap istilah statistika dengan artinya.",
          items: ["Mean", "Median", "Modus"],
          options: ["Rata-rata hitung", "Nilai tengah", "Nilai yang paling sering muncul", "Nilai terbesar"],
          kunci: [0, 1, 2],
          bahas: "Mean = rata-rata hitung; median = nilai tengah; modus = nilai yang paling sering muncul." },
        { tipe: "jodoh", q: "Pasangkan setiap data dengan jangkauannya (nilai terbesar dikurangi nilai terkecil).",
          items: ["3, 7, 5, 9", "10, 12, 10, 15", "6, 8, 6, 14"],
          options: ["6", "5", "8", "9"],
          kunci: [0, 1, 2],
          bahas: "9−3 = 6; 15−10 = 5; 14−6 = 8." },
        { tipe: "isian", q: "Rata-rata dari 6, 8, 10, 12 adalah ....",
          kunci: ["9"],
          bahas: "(6+8+10+12)/4 = 36/4 = 9." },
        { tipe: "isian", q: "Median dari data 3, 8, 5, 9, 7, 4 adalah ....",
          kunci: ["6"],
          bahas: "Terurut: 3, 4, 5, 7, 8, 9. Median = (5+7)/2 = 6." }
      ]
    },
    {
      id: "paket-09",
      judul: "Peluang",
      deskripsi: "Titik sampel, ruang sampel, peluang teoretis dan empiris.",
      soal: [
        { tipe: "pgk", q: "Sebuah dadu dilempar sekali. Pilih semua pernyataan yang BENAR.",
          options: ["P(mata 6) = 1/6", "P(mata genap) = 1/2", "P(mata prima) = 1/2", "P(mata ganjil) = 1/3"],
          kunci: [0, 1, 2],
          bahas: "P(6) = 1/6; P(genap {2,4,6}) = 3/6 = 1/2; P(prima {2,3,5}) = 3/6 = 1/2. P(ganjil) = 3/6 = 1/2, bukan 1/3." },
        { tipe: "pgk", q: "Dua koin dilempar bersamaan. Pilih semua pernyataan yang BENAR.",
          options: ["Ruang sampelnya memiliki 4 anggota", "P(dua-duanya angka) = 1/4", "P(satu angka satu gambar) = 1/2", "P(dua-duanya gambar) = 1/3"],
          kunci: [0, 1, 2],
          bahas: "Ruang sampel {AA, AG, GA, GG} beranggota 4. P(AA) = 1/4; P(satu angka satu gambar) = 2/4 = 1/2; P(GG) = 1/4, bukan 1/3." },
        { tipe: "pgk", q: "Dalam sebuah kantong ada 3 bola merah dan 2 bola biru. Satu bola diambil acak. Pilih semua pernyataan yang BENAR.",
          options: ["P(kuning) = 1/5", "P(merah) = 3/5", "P(biru) = 2/5", "P(merah) + P(biru) = 1"],
          kunci: [1, 2, 3],
          bahas: "P(merah) = 3/5, P(biru) = 2/5, jumlahnya 1. Tidak ada bola kuning sehingga P(kuning) = 0." },
        { tipe: "bs", q: "Pernyataan: Peluang suatu kejadian yang pasti terjadi adalah 1",
          kunci: true,
          bahas: "Benar. Kejadian pasti memiliki peluang 1 (100%)." },
        { tipe: "bs", q: "Pernyataan: Jika sebuah koin dilempar 10 kali dan selalu muncul gambar, peluang muncul angka pada lemparan ke-11 lebih besar dari 1/2",
          kunci: false,
          bahas: "Salah. Setiap lemparan saling bebas; peluang muncul angka tetap 1/2." },
        { tipe: "bs", q: "Pernyataan: P(A) + P(bukan A) = 1 untuk setiap kejadian A",
          kunci: true,
          bahas: "Benar. Peluang suatu kejadian ditambah peluang komplemennya selalu 1." },
        { tipe: "jodoh", q: "Pasangkan setiap percobaan dengan banyaknya titik sampel.",
          items: ["Melempar 1 dadu", "Melempar 2 koin", "Melempar 1 dadu dan 1 koin"],
          options: ["6", "4", "12", "8"],
          kunci: [0, 1, 2],
          bahas: "1 dadu: 6; 2 koin: 2×2 = 4; 1 dadu dan 1 koin: 6×2 = 12." },
        { tipe: "jodoh", q: "Pasangkan setiap kejadian pada pelemparan sebuah dadu dengan peluangnya.",
          items: ["Mata dadu 5", "Mata dadu genap", "Mata dadu lebih dari 4"],
          options: ["1/6", "1/2", "1/3", "2/3"],
          kunci: [0, 1, 2],
          bahas: "P(5) = 1/6; P(genap {2,4,6}) = 3/6 = 1/2; P(lebih dari 4 {5,6}) = 2/6 = 1/3." },
        { tipe: "isian", q: "Sebuah dadu dilempar sekali. Peluang muncul mata dadu faktor dari 6 adalah ....",
          kunci: ["2/3", "4/6"],
          bahas: "Faktor dari 6: {1, 2, 3, 6}, ada 4 dari 6 kemungkinan, jadi 4/6 = 2/3." },
        { tipe: "isian", q: "Dari 40 kali pelemparan koin, muncul angka 22 kali. Frekuensi relatif muncul gambar adalah ....",
          kunci: ["0,45", "0.45", "9/20"],
          bahas: "Gambar muncul 40−22 = 18 kali, frekuensi relatifnya 18/40 = 0,45." }
      ]
    }
  ]
};
